# Generated by Django 2.2.16 on 2022-05-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='titless', to='reviews.Genre'),
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
