# Generated by Django 2.2.16 on 2022-05-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220517_1831'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='valid_rate',
        ),
    ]
